name: Docker Publish

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          debug: true

      - name: Build Docker Image
        uses: actions/checkout@v4
        

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "hemilkumarpansuriya" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile  # Path to your Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/projects/helloapp:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/projects/helloapp:${{ github.sha }}
