name: Docker Publish

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          debug: true

      - name: Build Docker Image
        uses: actions/checkout@v3
        

      - name: Login to Docker Hub
        
        run: docker login -u hemilkumarpansuriya
        with:
          username: ${{ secrets.hemilkumarpansuriya }}
          password: ${{ secrets.dckr_pat_Lw9i9AmnnCugBEuwcbKDM6ZJJts }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile  # Path to your Dockerfile
          push: true
          tags: |
            hemilkumarpansuriya/projects/helloapp:latest
            hemilkumarpansuriya/projects/helloapp:${{ github.sha }}
